# Generated by Django 6.0 on 2025-12-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcreport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_reports', to='plant.productionbatch'),
        ),
    ]
