# Generated by Django 6.0 on 2025-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_document_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
