# Generated by Django 6.0 on 2025-12-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_batch_remove_documentchunk_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AlterModelOptions(
            name='productionbatch',
            options={'verbose_name': 'Production Batch', 'verbose_name_plural': 'Production Batches'},
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='is_anomaly',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
